import Head from "next/head";
import { PostCard, Categories, PostWidget } from "../components";
import { getPost } from "../services";
export default function Home({ posts }) {
	return (
		<div className="container mx-auto px-10 mb-8">
			<Head>
				<title>CMS Blog</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
				<div className="col-span-1 lg:col-span-8">
					{posts.map((post, index) => (
						<PostCard post={post} key={index} />
					))}
				</div>
				<div className="col-span-1 lg:col-span-4">
					<div className="relative lg:sticky top-8 ">
						<PostWidget />
						<Categories />
					</div>
				</div>
			</div>
		</div>
	);
}

export async function getStaticProps() {
	const posts = (await getPost()) || [];
	return {
		props: { posts },
	};
}
